"""Dukascopy symbols supported by datagrab tickterial source."""

from __future__ import annotations

# discovered_at = 2026-03-03T17:09:20.229169+00:00

SYMBOL_CATEGORIES: dict[str, list[str]] = {
    'fx_crosses': [
        'AEDCNH',
        'AEDCZK',
        'AEDHKD',
        'AEDHUF',
        'AEDJPY',
        'AEDMXN',
        'AEDRON',
        'AEDSAR',
        'AEDTHB',
        'AEDTRY',
        'AEDZAR',
        'AUDAED',
        'AUDCAD',
        'AUDCHF',
        'AUDCNH',
        'AUDCZK',
        'AUDDKK',
        'AUDHKD',
        'AUDHUF',
        'AUDILS',
        'AUDJPY',
        'AUDMXN',
        'AUDNOK',
        'AUDNZD',
        'AUDPLN',
        'AUDRON',
        'AUDSAR',
        'AUDSEK',
        'AUDSGD',
        'AUDTHB',
        'AUDTRY',
        'AUDZAR',
        'CADAED',
        'CADCHF',
        'CADCNH',
        'CADCZK',
        'CADDKK',
        'CADHKD',
        'CADHUF',
        'CADILS',
        'CADJPY',
        'CADMXN',
        'CADNOK',
        'CADPLN',
        'CADRON',
        'CADSAR',
        'CADSEK',
        'CADSGD',
        'CADTHB',
        'CADTRY',
        'CADZAR',
        'CHFAED',
        'CHFCNH',
        'CHFCZK',
        'CHFDKK',
        'CHFHKD',
        'CHFHUF',
        'CHFILS',
        'CHFJPY',
        'CHFMXN',
        'CHFNOK',
        'CHFPLN',
        'CHFRON',
        'CHFSAR',
        'CHFSEK',
        'CHFSGD',
        'CHFTHB',
        'CHFTRY',
        'CHFZAR',
        'CNHCZK',
        'CNHHKD',
        'CNHHUF',
        'CNHJPY',
        'CNHMXN',
        'CNHTHB',
        'CNHTRY',
        'CNHZAR',
        'CZKHUF',
        'CZKJPY',
        'CZKTHB',
        'CZKTRY',
        'DKKAED',
        'DKKCNH',
        'DKKCZK',
        'DKKHKD',
        'DKKHUF',
        'DKKILS',
        'DKKJPY',
        'DKKMXN',
        'DKKRON',
        'DKKSAR',
        'DKKTHB',
        'DKKTRY',
        'DKKZAR',
        'EURAED',
        'EURAUD',
        'EURCAD',
        'EURCHF',
        'EURCNH',
        'EURCZK',
        'EURDKK',
        'EURGBP',
        'EURHKD',
        'EURHUF',
        'EURILS',
        'EURJPY',
        'EURMXN',
        'EURNOK',
        'EURNZD',
        'EURPLN',
        'EURRON',
        'EURSAR',
        'EURSEK',
        'EURSGD',
        'EURTHB',
        'EURTRY',
        'EURZAR',
        'GBPAED',
        'GBPAUD',
        'GBPCAD',
        'GBPCHF',
        'GBPCNH',
        'GBPCZK',
        'GBPDKK',
        'GBPHKD',
        'GBPHUF',
        'GBPILS',
        'GBPJPY',
        'GBPMXN',
        'GBPNOK',
        'GBPNZD',
        'GBPPLN',
        'GBPRON',
        'GBPSAR',
        'GBPSEK',
        'GBPSGD',
        'GBPTHB',
        'GBPTRY',
        'GBPZAR',
        'HKDCZK',
        'HKDHUF',
        'HKDJPY',
        'HKDMXN',
        'HKDTHB',
        'HKDTRY',
        'HKDZAR',
        'ILSAED',
        'ILSCNH',
        'ILSCZK',
        'ILSHKD',
        'ILSHUF',
        'ILSJPY',
        'ILSMXN',
        'ILSRON',
        'ILSSAR',
        'ILSTHB',
        'ILSTRY',
        'ILSZAR',
        'JPYHUF',
        'MXNCZK',
        'MXNHUF',
        'MXNJPY',
        'MXNTHB',
        'MXNTRY',
        'NOKAED',
        'NOKCNH',
        'NOKCZK',
        'NOKDKK',
        'NOKHKD',
        'NOKHUF',
        'NOKILS',
        'NOKJPY',
        'NOKMXN',
        'NOKRON',
        'NOKSAR',
        'NOKSEK',
        'NOKTHB',
        'NOKTRY',
        'NOKZAR',
        'NZDAED',
        'NZDCAD',
        'NZDCHF',
        'NZDCNH',
        'NZDCZK',
        'NZDDKK',
        'NZDHKD',
        'NZDHUF',
        'NZDILS',
        'NZDJPY',
        'NZDMXN',
        'NZDNOK',
        'NZDPLN',
        'NZDRON',
        'NZDSAR',
        'NZDSEK',
        'NZDSGD',
        'NZDTHB',
        'NZDTRY',
        'NZDZAR',
        'PLNAED',
        'PLNCNH',
        'PLNCZK',
        'PLNDKK',
        'PLNHKD',
        'PLNHUF',
        'PLNILS',
        'PLNJPY',
        'PLNMXN',
        'PLNNOK',
        'PLNRON',
        'PLNSAR',
        'PLNSEK',
        'PLNTHB',
        'PLNTRY',
        'PLNZAR',
        'RONCNH',
        'RONCZK',
        'RONHKD',
        'RONHUF',
        'RONJPY',
        'RONMXN',
        'RONTHB',
        'RONTRY',
        'RONZAR',
        'SARCNH',
        'SARCZK',
        'SARHKD',
        'SARHUF',
        'SARJPY',
        'SARMXN',
        'SARRON',
        'SARTHB',
        'SARTRY',
        'SARZAR',
        'SEKAED',
        'SEKCNH',
        'SEKCZK',
        'SEKDKK',
        'SEKHKD',
        'SEKHUF',
        'SEKILS',
        'SEKJPY',
        'SEKMXN',
        'SEKRON',
        'SEKSAR',
        'SEKTHB',
        'SEKTRY',
        'SEKZAR',
        'SGDAED',
        'SGDCNH',
        'SGDCZK',
        'SGDDKK',
        'SGDHKD',
        'SGDHUF',
        'SGDILS',
        'SGDJPY',
        'SGDMXN',
        'SGDNOK',
        'SGDPLN',
        'SGDRON',
        'SGDSAR',
        'SGDSEK',
        'SGDTHB',
        'SGDTRY',
        'SGDZAR',
        'THBHUF',
        'THBJPY',
        'TRYHUF',
        'TRYJPY',
        'TRYTHB',
        'USDAED',
        'USDCNH',
        'USDCZK',
        'USDDKK',
        'USDHKD',
        'USDHUF',
        'USDILS',
        'USDMXN',
        'USDNOK',
        'USDPLN',
        'USDRON',
        'USDSAR',
        'USDSEK',
        'USDSGD',
        'USDTHB',
        'USDTRY',
        'USDZAR',
        'ZARCZK',
        'ZARHUF',
        'ZARJPY',
        'ZARMXN',
        'ZARTHB',
        'ZARTRY',
    ],
    'fx_majors': [
        'AUDUSD',
        'EURUSD',
        'GBPUSD',
        'NZDUSD',
        'USDCAD',
        'USDCHF',
        'USDJPY',
    ],
    'fx_metals': [
        'XAGAED',
        'XAGAUD',
        'XAGCAD',
        'XAGCHF',
        'XAGCNH',
        'XAGCZK',
        'XAGDKK',
        'XAGEUR',
        'XAGGBP',
        'XAGHKD',
        'XAGHUF',
        'XAGILS',
        'XAGJPY',
        'XAGMXN',
        'XAGNOK',
        'XAGNZD',
        'XAGPLN',
        'XAGRON',
        'XAGSAR',
        'XAGSEK',
        'XAGSGD',
        'XAGTHB',
        'XAGTRY',
        'XAGUSD',
        'XAGZAR',
        'XAUAED',
        'XAUAUD',
        'XAUCAD',
        'XAUCHF',
        'XAUCNH',
        'XAUCZK',
        'XAUDKK',
        'XAUEUR',
        'XAUGBP',
        'XAUHKD',
        'XAUHUF',
        'XAUILS',
        'XAUJPY',
        'XAUMXN',
        'XAUNOK',
        'XAUNZD',
        'XAUPLN',
        'XAURON',
        'XAUSAR',
        'XAUSEK',
        'XAUSGD',
        'XAUTHB',
        'XAUTRY',
        'XAUUSD',
        'XAUXAG',
        'XAUZAR',
    ],
    'cmd_agricultural': [
        'COCOACMDUSD',
        'COFFEECMDUSX',
        'COTTONCMDUSX',
        'OJUICECMDUSX',
        'SOYBEANCMDUSX',
        'SUGARCMDUSD',
    ],
    'cmd_energy': [
        'BRENTCMDUSD',
        'DIESELCMDUSD',
        'GASCMDUSD',
        'LIGHTCMDUSD',
    ],
    'cmd_metals': [
        'COPPERCMDUSD',
        'XPDCMDUSD',
        'XPTCMDUSD',
    ],
    'idx_africa': [
        'SOAIDXZAR',
    ],
    'idx_america': [
        'DOLLARIDXUSD',
        'USA30IDXUSD',
        'USA500IDXUSD',
        'USATECHIDXUSD',
        'USSC2000IDXUSD',
        'VOLIDXUSD',
    ],
    'idx_asia': [
        'AUSIDXAUD',
        'CHIIDXUSD',
        'HKGIDXHKD',
        'INDIDXUSD',
        'JPNIDXJPY',
        'SGDIDXSGD',
    ],
    'idx_europe': [
        'CHEIDXCHF',
        'DEUIDXEUR',
        'ESPIDXEUR',
        'EUSIDXEUR',
        'FRAIDXEUR',
        'GBRIDXGBP',
        'ITAIDXEUR',
        'NLDIDXEUR',
        'PLNIDXPLN',
    ],
    'bnd_cfd': [
        'BUNDTREUR',
        'UKGILTTRGBP',
        'USTBONDTRUSD',
    ],
    'vccy': [
        'ADAUSD',
        'AVEUSD',
        'BATUSD',
        'BCHCHF',
        'BCHEUR',
        'BCHGBP',
        'BCHUSD',
        'BTCCHF',
        'BTCEUR',
        'BTCGBP',
        'BTCUSD',
        'CMPUSD',
        'DSHUSD',
        'ENJUSD',
        'EOSUSD',
        'ETHCHF',
        'ETHEUR',
        'ETHGBP',
        'ETHUSD',
        'LNKUSD',
        'LTCCHF',
        'LTCEUR',
        'LTCGBP',
        'LTCUSD',
        'MATUSD',
        'MKRUSD',
        'TRXUSD',
        'UNIUSD',
        'XLMCHF',
        'XLMEUR',
        'XLMGBP',
        'XLMUSD',
        'YFIUSD',
    ],
}

SYMBOLS: list[str] = sorted(set(
    s for bucket in SYMBOL_CATEGORIES.values() for s in bucket
))

SYMBOL_COUNT = len(SYMBOLS)
CATEGORY_COUNT = len(SYMBOL_CATEGORIES)


def as_set() -> set[str]:
    return set(SYMBOLS)


def refresh_from_dukascopy(
    categories: list[str] | None = None,
    timeout: float = 30.0,
) -> dict[str, list[str]]:
    """Fetch the latest instrument list from dukascopy-node.app.

    Args:
        categories: Category slugs to update (None = all from SYMBOL_CATEGORIES).
        timeout: HTTP request timeout in seconds.

    Returns:
        Updated SYMBOL_CATEGORIES dict.

    Raises:
        FetchError: If the network request fails or the page structure changed.
    """
    import json
    import re
    import ssl
    import urllib.request

    from .exceptions import FetchError

    base_url = "https://www.dukascopy-node.app/instruments"
    target_categories = categories or list(SYMBOL_CATEGORIES.keys())
    result: dict[str, list[str]] = {}

    ctx = ssl.create_default_context()

    for cat in target_categories:
        url = f"{base_url}/{cat}"
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "datagrab/symbols-updater"})
            with urllib.request.urlopen(req, timeout=timeout, context=ctx) as resp:
                html = resp.read().decode("utf-8", "ignore")
        except (urllib.error.URLError, OSError, TimeoutError) as exc:
            raise FetchError(f"failed to fetch {url}: {exc}") from exc

        symbols: list[str] = []
        for match in re.finditer(r'"id"\s*:\s*"([A-Za-z0-9.+#/-]+)"', html):
            raw_id = match.group(1).upper().replace("/", "")
            if raw_id and len(raw_id) <= 20:
                symbols.append(raw_id)
        symbols = sorted(set(symbols))
        if not symbols:
            raise FetchError(f"no symbols found for category '{cat}' — page structure may have changed")
        result[cat] = symbols

    return result